### ISSUE TITLE
pull up to refresh

### ISSUE THREAD

**Issue by DanielDanielDanielD** [BoxFactura/pulltorefresh.js#105]
Hi, thanks for sharing this library.

I'm trying to create such an option that the user pulls up the bottom of the page a particular event is created, how can I achieve this option with this library?

**Comment by faelsoto** [comment]
I don't think this would be within the scope for this library, as it's intended for a quick way to implement or reimplement pull to refresh. I'm sure that you can achieve what you're looking for by hacking the library, and maybe implement some kind of config for it (and maybe a PR).

Otherwise it's not supported out of the box.

**Comment by DanielDanielDanielD** [comment]
I understand, thanks for your reply anyway.
