### ISSUE TITLE
chrome defaults touch events as passive

### ISSUE THREAD

**Issue by UziTech** [BoxFactura/pulltorefresh.js#3]
if you test out the demos in chrome you will see this in the console:

```
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```

https://www.chromestatus.com/features/5093566007214080

states that chrome treats touch events as passive by default to avoid scroll delays.

The fix would be to add the `{ passive: false }` option to any `addEventListener` calls the could use `preventDefault()`

**Comment by pateketrueke** [comment]
Thanks for catching this!

**Comment by RByers** [comment]
As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway.  Your fix may cause problems on browsers which don't support passing options to `addEventListener` because you didn't use [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

**Comment by faelsoto** [comment]
I'm not 100% familiar with this issue, as you are. Could you create a PR with the proposed changes?

**Comment by RByers** [comment]
See #15

**Comment by davidalee** [comment]
Running into this issue as well. https://github.com/BoxFactura/pulltorefresh.js/pull/15 seems to resolve this issue (don't want to explicitly set the passive flag on the listener).

**Comment by pateketrueke** [comment]
I'm reviewing #15 and I see we need the ability to enable/disable passive listeners as an option, otherwise this issue (#3) will pop up again.

If the PR #15 actually solves the same issue without warnings I'll merge it without doubts.

@davidalee can you test both scenarios?

**Comment by davidalee** [comment]
@pateketrueke Just tested it locally. I'm not seeing any warnings in the browser, and this also resolves https://github.com/BoxFactura/pulltorefresh.js/issues/18 where the `touchmove` listener still existed even after destroying everything.

**Comment by davidalee** [comment]
Scratch that, I am seeing the warnings. It seems it'd be better to expose the option to enable/disable passive listeners.

**Comment by UziTech** [comment]
would it be better to to [check for support](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) for `passive`

```javascript
let supportsPassive = false;
try {
  window.addEventListener("test", null, { get passive() { supportsPassive = true }});
} catch(e) {}
...
window.addEventListener('touchmove', _onTouchMove, (supportsPassive ? { passive: false } : false));
...
window.removeEventListener('touchmove', handlers.onTouchMove, (supportsPassive ? { passive: false } : false));
```
