### ISSUE TITLE
Desktop/Mouse support?

### ISSUE THREAD

**Issue by afturner** [BoxFactura/pulltorefresh.js#41]
Hey there! Has anyone attempted to implement desktop or mouse support? I imagine that it would be at least slightly contentious due to altering default scroll behavior; however, I'm sure there's a good way to make it fluid and work properly. 

May take a look myself later today, but thought I'd see what others think

**Comment by faelsoto** [comment]
Hey! Check out our demos, we've included the touch emulator from hammer.js, so maybe that's what you're looking for.

**Comment by jancborchardt** [comment]
The touch emulator requires clicking and dragging, which is not really something you do on desktop. What I assume @afturner means (and what I’d really like too) is that simply scrolling on desktop has the same effect as, well, scrolling on mobile.

(Because no pull to refresh library so far does both, and we always have to manually implement it.)

**Comment by faelsoto** [comment]
To be honest I haven't seen anything like that, and that's not the focus for this library.

But feel free to fork it!
